language: node_js

sudo: false

node_js:
  - stable
  - 12
  - 10
  - 8

script:
  - >
    version=`node --version | cut -d 'v' -f 2 | cut -d '.' -f 1`

    if [ $version -eq 14 ]; then
      npm run lint
      npm run spellcheck
      npm run test -- --coverage --coverage-report=text-lcov --reporter=classic --color
    else
      echo "*** skip other commands to speed up build ***"
      npm run test
    fi;
